name: i_am_rich
description: "Lab 1 - I Am Rich: ứng dụng Flutter hiển thị viên kim cương."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
